# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: BootProj11_InjectingSpecialValuesToSpringbeanProperties
emp:
  details:
    eno: 101
    ename: raja
    eaddrs: hyd
    favColors: red,blue,yellow,cyan
    nickNames: chunty,bunty,sunty
    phoneNumbers: 999999,888888,777777
    idDetails:
      aadharNo: 1234567
      voterId: 456937
      panNo: 748596
    project:
      pid: 1234567
      pname: OpenFx
      paddrs: hyd
      size: 100
